import path from "node:path";
import {
  CharaCardV3Schema,
  ManifestSchema,
  PresetImportSchema,
  RegexImportSchema,
  WorldbookImportSchema
} from "./schemas.js";
import { ensureDir, sha256, writeJson, writeText } from "./fs.js";
import { buildArWidgetHtml, makeArWidgetRegex } from "./widget.js";

export interface BuildAssetsOptions {
  outDir?: string;
  suiteId?: string;
  now?: Date;
}

export interface BuiltAssets {
  outDir: string;
  suiteId: string;
  files: Array<{ kind: string; path: string; sha256: string }>;
}

const defaultOutDir = path.resolve("dist/tavo-import");

function stamp(date: Date): string {
  return date.toISOString().replace(/[:.]/g, "-");
}

function baseEntry(uid: number, comment: string, content: string, key: string[]) {
  return {
    uid,
    key,
    keysecondary: [],
    comment,
    content,
    constant: true,
    vectorized: false,
    selective: false,
    selectiveLogic: 0,
    addMemo: true,
    order: 100,
    position: 0,
    disable: false,
    excludeRecursion: false,
    preventRecursion: false,
    delayUntilRecursion: false,
    probability: 100,
    matchWholeWords: false,
    useProbability: true,
    depth: 4,
    group: "",
    groupOverride: false,
    groupWeight: 100,
    scanDepth: null,
    caseSensitive: null,
    automationId: "",
    role: null,
    sticky: 0,
    cooldown: 0,
    delay: 0,
    displayIndex: uid
  };
}

export function makeDirectArHtml(suiteId: string): string {
  return `<div id="${suiteId}-ar-status" style="margin:8px 0;padding:8px 10px;border:1px solid #d99;border-radius:8px;color:#933;background:#fff3f3;font-size:13px;line-height:1.5;">${suiteId}: AR JS 未执行</div>
<script>
(async function(){
  var id=${JSON.stringify(suiteId)};
  var el=document.getElementById(id+'-ar-status');
  function say(t,ok){if(el){el.textContent=id+': '+t;el.style.color=ok?'#27632a':'#933';el.style.borderColor=ok?'#8bc58f':'#d99';el.style.background=ok?'#f1fff2':'#fff3f3';}}
  try{
    if(!(window.tavo&&tavo.set&&tavo.get&&tavo.memory&&tavo.memory.current&&tavo.memory.update)){say('找不到完整 tavo JS API',false);return;}
    tavo.set('devkit.arDirect', 'ok', 'chat');
    var mem=await tavo.memory.current();
    if(!mem){say('当前聊天没有 memory 对象',false);return;}
    if(!Array.isArray(mem.memories)) mem.memories=[];
    var item='['+id+'] AR_DIRECT_OK';
    mem.memories=mem.memories.filter(function(x){return String(x).indexOf('['+id+'] AR_DIRECT_OK')!==0;});
    mem.memories.push(item);
    mem.enabled=true;
    await tavo.memory.update(mem);
    try{tavo.utils.toast(id+' AR direct ok');}catch(_){}
    say('AR JS 已执行并写入长记忆',true);
  }catch(e){say('JS 报错: '+(e&&e.message?e.message:e),false);}
})();
</script>`;
}

function makeRegexExecutionHtml(suiteId: string): string {
  const ok = "String.fromCharCode(82,69,71,69,88,95,74,83,95,79,75)";
  const noTavo = "String.fromCharCode(78,79,95,84,65,86,79,95,82,69,71,69,88)";
  const err = "String.fromCharCode(82,69,71,69,88,95,74,83,95,69,82,82)";
  const key = "String.fromCharCode(100,101,118,107,105,116,46,114,101,103,101,120,74,115)";
  const value = "String.fromCharCode(111,107)";
  const scope = "String.fromCharCode(99,104,97,116)";
  return `<div id="${suiteId}-regex-js-status" style="margin:8px 0;padding:8px 10px;border:1px solid #d99;border-radius:8px;color:#933;background:#fff3f3;font-size:13px;line-height:1.5;">REGEX_JS_PENDING</div><script>(function(){try{var el=document.getElementById(${JSON.stringify(`${suiteId}-regex-js-status`)});if(window.tavo&&tavo.set){tavo.set(${key},${value},${scope});if(el)el.textContent=${ok}}else{if(el)el.textContent=${noTavo}}}catch(e){try{var el=document.getElementById(${JSON.stringify(`${suiteId}-regex-js-status`)});if(el)el.textContent=${err}}catch(_){}}})()</script>`;
}

export function makeRegexImport(suiteId: string) {
  return [
    {
      id: `${suiteId}-regex-js-execution`,
      scriptName: `${suiteId} Regex JS Execution`,
      findRegex: "CODEX_DEVKIT_REGEX_JS",
      replaceString: makeRegexExecutionHtml(suiteId),
      trimStrings: [],
      placement: [1, 2],
      placements: ["user", "char"],
      disabled: false,
      enabled: true,
      markdownOnly: true,
      promptOnly: false,
      runOnEdit: false,
      timing: "display",
      substituteRegex: 0,
      substitution: "none",
      minDepth: null,
      maxDepth: null
    }
  ];
}

export function makeCharacterCard(suiteId: string) {
  return {
    spec: "chara_card_v3",
    spec_version: "3.0",
    data: {
      name: `${suiteId} 角色`,
      description: `用于 Tavo Dev Kit 自动化回归的临时角色。发送 CODEX_DEVKIT_REGEX_JS 可测试正则注入 JS。`,
      first_mes: `${suiteId} 角色已启动。\nCODEX_DEVKIT_REGEX_JS`,
      personality: "测试角色，回复简短。",
      scenario: "Tavo Dev Kit regression sandbox.",
      mes_example: "",
      creator_notes: "Generated by local tavo-dev-kit. Safe to keep as test artifact.",
      system_prompt: "",
      post_history_instructions: "",
      alternate_greetings: null,
      character_book: null,
      tags: ["codex-devkit", "test"],
      creator: "codex",
      character_version: "v1",
      extensions: {}
    }
  };
}

export function makeWorldbook(suiteId: string) {
  return {
    name: `${suiteId} 世界书`,
    entries: {
      "0": baseEntry(0, "codex-devkit 常驻记录", `[${suiteId}] 世界书导入成功。`, ["codex-devkit", suiteId]),
      "1": baseEntry(1, "codex-devkit JS 结果归档", `[${suiteId}] JS 探针结果保留区。`, ["REGEX_JS_OK", "AR_DIRECT_OK"])
    }
  };
}

export function makePreset(suiteId: string) {
  const prompt = {
    identifier: `${suiteId}-system`,
    name: `${suiteId} 系统探针`,
    system_prompt: false,
    marker: false,
    content: `你是 Tavo Dev Kit 回归测试角色。保持回复简短，不要主动改写 CODEX_DEVKIT_REGEX_JS 探针文本。`,
    role: "system",
    injection_position: 0,
    injection_depth: 4,
    forbid_overrides: false,
    enabled: true
  };
  return {
    prompts: [prompt],
    prompt_order: [
      {
        character_id: 100001,
        order: [{ identifier: prompt.identifier, enabled: true }]
      }
    ],
    new_chat_prompt: "",
    new_group_chat_prompt: "[Start a new group chat. Group members: {{group}}]",
    new_example_chat_prompt: "[Example Chat]",
    continue_nudge_prompt: "[Continue the following message: {{lastChatMessage}}]",
    impersonation_prompt: "[Write your next reply from the point of view of {{user}}.]",
    group_nudge_prompt: "[Write the next reply only as the group members.]",
    scenario_format: "[Circumstances and context of the dialogue: {{scenario}}]",
    personality_format: "[{{char}}'s personality: {{personality}}]",
    wi_format: "{0}"
  };
}

export async function buildTavoAssets(options: BuildAssetsOptions = {}): Promise<BuiltAssets> {
  const now = options.now ?? new Date();
  const suiteId = options.suiteId ?? `codex-devkit-${stamp(now)}`;
  const outDir = path.resolve(options.outDir ?? defaultOutDir);
  await ensureDir(outDir);

  const assets = [
    { kind: "character", filename: `${suiteId}.card.json`, data: makeCharacterCard(suiteId), schema: CharaCardV3Schema },
    { kind: "worldbook", filename: `${suiteId}.worldbook.json`, data: makeWorldbook(suiteId), schema: WorldbookImportSchema },
    { kind: "regex", filename: `${suiteId}.regex.json`, data: makeRegexImport(suiteId), schema: RegexImportSchema },
    { kind: "preset", filename: `${suiteId}.preset.json`, data: makePreset(suiteId), schema: PresetImportSchema }
  ];

  const validation: Array<{ kind: string; ok: boolean; message: string }> = [];
  const files: BuiltAssets["files"] = [];
  for (const asset of assets) {
    const result = asset.schema.safeParse(asset.data);
    validation.push({
      kind: asset.kind,
      ok: result.success,
      message: result.success ? "ok" : result.error.issues.map((issue) => issue.message).join("; ")
    });
    if (!result.success) throw new Error(`${asset.kind} schema validation failed: ${validation.at(-1)?.message}`);
    const file = path.join(outDir, asset.filename);
    await writeJson(file, asset.data);
    files.push({ kind: asset.kind, path: file, sha256: await sha256(file) });
  }

  const arFile = path.join(outDir, `${suiteId}.ar-direct.html`);
  await writeText(arFile, makeDirectArHtml(suiteId));
  files.push({ kind: "ar-direct-html", path: arFile, sha256: await sha256(arFile) });

  const widget = await buildArWidgetHtml({ suiteId });
  const widgetFile = path.join(outDir, `${suiteId}.ar-widget.html`);
  await writeText(widgetFile, widget.html);
  files.push({ kind: "ar-widget-html", path: widgetFile, sha256: await sha256(widgetFile) });

  const widgetRegex = makeArWidgetRegex(suiteId, widget.html);
  const widgetRegexResult = RegexImportSchema.safeParse(widgetRegex);
  validation.push({
    kind: "ar-widget-regex",
    ok: widgetRegexResult.success,
    message: widgetRegexResult.success ? "ok" : widgetRegexResult.error.issues.map((issue) => issue.message).join("; ")
  });
  if (!widgetRegexResult.success) throw new Error(`${validation.at(-1)?.kind} schema validation failed: ${validation.at(-1)?.message}`);
  const widgetRegexFile = path.join(outDir, `${suiteId}.ar-widget.regex.json`);
  await writeJson(widgetRegexFile, widgetRegex);
  files.push({ kind: "ar-widget-regex", path: widgetRegexFile, sha256: await sha256(widgetRegexFile) });

  const manifest = {
    suiteId,
    generatedAt: now.toISOString(),
    files,
    validation
  };
  ManifestSchema.parse(manifest);
  const manifestFile = path.join(outDir, `${suiteId}.manifest.json`);
  await writeJson(manifestFile, manifest);
  files.push({ kind: "manifest", path: manifestFile, sha256: await sha256(manifestFile) });

  const reportFile = path.join(outDir, `${suiteId}.test-report.json`);
  await writeJson(reportFile, {
    suiteId,
    generatedAt: now.toISOString(),
    status: "static pass",
    notes: [
      "Generated from tavo-complete official API boundary and local import fixtures.",
      "Emulator verification is recorded separately under reports/latest."
    ]
  });
  files.push({ kind: "test-report", path: reportFile, sha256: await sha256(reportFile) });

  return { outDir, suiteId, files };
}
